apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: metacity
type: Opaque
data:
  pg-connection: base64KeyConnection #Обязательно заворачиваем в base64 строку подключения
  server-secret: base64SecretKey #По аналогии