# аплаим стандартный cert-manager
# kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alexey.k@4taleproduction.com
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
      - http01:
          ingress:
            class: nginx