// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protoc-gen-swagger/options/annotations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.Gateway.ProtocGenOpenapiv2.Options {

  /// <summary>Holder for reflection information generated from protoc-gen-swagger/options/annotations.proto</summary>
  public static partial class AnnotationsReflection {

    #region Descriptor
    /// <summary>File descriptor for protoc-gen-swagger/options/annotations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnotationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90b2MtZ2VuLXN3YWdnZXIvb3B0aW9ucy9hbm5vdGF0aW9ucy5wcm90",
            "bxIpZ3JwYy5nYXRld2F5LnByb3RvY19nZW5fb3BlbmFwaXYyLm9wdGlvbnMa",
            "IGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvGixwcm90b2MtZ2Vu",
            "LW9wZW5hcGl2Mi9vcHRpb25zL29wZW5hcGl2Mi5wcm90bzpsChFvcGVuYXBp",
            "djJfc3dhZ2dlchIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxiSCCAB",
            "KAsyMi5ncnBjLmdhdGV3YXkucHJvdG9jX2dlbl9vcGVuYXBpdjIub3B0aW9u",
            "cy5Td2FnZ2VyOnIKE29wZW5hcGl2Ml9vcGVyYXRpb24SHi5nb29nbGUucHJv",
            "dG9idWYuTWV0aG9kT3B0aW9ucxiSCCABKAsyNC5ncnBjLmdhdGV3YXkucHJv",
            "dG9jX2dlbl9vcGVuYXBpdjIub3B0aW9ucy5PcGVyYXRpb246bQoQb3BlbmFw",
            "aXYyX3NjaGVtYRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiS",
            "CCABKAsyMS5ncnBjLmdhdGV3YXkucHJvdG9jX2dlbl9vcGVuYXBpdjIub3B0",
            "aW9ucy5TY2hlbWE6ZwoNb3BlbmFwaXYyX3RhZxIfLmdvb2dsZS5wcm90b2J1",
            "Zi5TZXJ2aWNlT3B0aW9ucxiSCCABKAsyLi5ncnBjLmdhdGV3YXkucHJvdG9j",
            "X2dlbl9vcGVuYXBpdjIub3B0aW9ucy5UYWc6bgoPb3BlbmFwaXYyX2ZpZWxk",
            "Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxiSCCABKAsyNS5ncnBj",
            "LmdhdGV3YXkucHJvdG9jX2dlbl9vcGVuYXBpdjIub3B0aW9ucy5KU09OU2No",
            "ZW1hQkhaRmdpdGh1Yi5jb20vZ3JwYy1lY29zeXN0ZW0vZ3JwYy1nYXRld2F5",
            "L3YyL3Byb3RvYy1nZW4tb3BlbmFwaXYyL29wdGlvbnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Openapiv2Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { AnnotationsExtensions.Openapiv2Swagger, AnnotationsExtensions.Openapiv2Operation, AnnotationsExtensions.Openapiv2Schema, AnnotationsExtensions.Openapiv2Tag, AnnotationsExtensions.Openapiv2Field }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of protoc-gen-swagger/options/annotations.proto</summary>
  public static partial class AnnotationsExtensions {
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Swagger> Openapiv2Swagger =
      new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Swagger>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Swagger.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Operation> Openapiv2Operation =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Operation>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Operation.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Schema> Openapiv2Schema =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Schema>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Schema.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Tag> Openapiv2Tag =
      new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Tag>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.Tag.Parser));
    /// <summary>
    /// ID assigned by protobuf-global-extension-registry@google.com for gRPC-Gateway project.
    ///
    /// All IDs are the same, as assigned. It is okay that they are the same, as they extend
    /// different descriptor messages.
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.JSONSchema> Openapiv2Field =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.JSONSchema>(1042, pb::FieldCodec.ForMessage(8338, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.JSONSchema.Parser));
  }

}

#endregion Designer generated code
