// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoDaoBackend.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoDaoBackend.Migrations
{
    [DbContext(typeof(NeoDaoDbContext))]
    [Migration("20240927125955_NFTStore")]
    partial class NFTStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoDaoBackend.Models.db.Auction", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<DateTimeOffset>("AuctionEndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auction_end_time")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTimeOffset>("AuctionStartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auction_start_time")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTimeOffset>("LotsStartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lots_start_time")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("AuctionId");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.AuctionLot", b =>
                {
                    b.Property<Guid>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<int>("CoinType")
                        .HasColumnType("int")
                        .HasColumnName("coin_type");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<Guid?>("CurrentBidUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_bid_user_id");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<decimal>("InitialPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_price");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<DateTimeOffset?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LotId")
                        .HasName("PK_auction_lots");

                    b.HasIndex("AuctionId");

                    b.HasIndex("CurrentBidUserId")
                        .HasDatabaseName("auction_lots_current_bid_user_idx");

                    b.HasIndex("InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("auction_lots_inventory_item_idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("auction_lots_user_idx");

                    b.ToTable("auction_lots", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Channel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("userA");

                    b.Property<Guid?>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("userB");

                    b.Property<bool>("isReadA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isReadA");

                    b.Property<bool>("isReadB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isReadB");

                    b.HasKey("ChannelId")
                        .HasName("channels_pkey");

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("channels", (string)null);

                    b.HasData(
                        new
                        {
                            ChannelId = "global",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            isReadA = false,
                            isReadB = false
                        },
                        new
                        {
                            ChannelId = "admin",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            isReadA = false,
                            isReadB = false
                        },
                        new
                        {
                            ChannelId = "greetings",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            isReadA = false,
                            isReadB = false
                        });
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.ChatMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("MessageId")
                        .HasName("messages_pkey");

                    b.HasIndex("ChannelId");

                    b.HasIndex("SenderId");

                    b.ToTable("chat_messages", (string)null);

                    b.HasData(
                        new
                        {
                            MessageId = 1L,
                            ChannelId = "greetings",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Message = "Welcome to Neo Dao"
                        });
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Equipment", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("InventoryId", "SlotType")
                        .HasName("equipments_pkey");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("idx_equipment_item_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.FreeTradeItem", b =>
                {
                    b.Property<string>("UnrealId")
                        .HasColumnType("text")
                        .HasColumnName("unreal_id");

                    b.Property<int>("NetCost")
                        .HasColumnType("integer")
                        .HasColumnName("net_cost");

                    b.HasKey("UnrealId");

                    b.ToTable("free_trade_items", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("group_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LeaderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_user_id");

                    b.HasKey("GroupId");

                    b.HasIndex("LeaderUserId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InventoryId")
                        .HasName("inventory_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_unique_user")
                        .IsUnique();

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("MetaforceNftId")
                        .HasColumnType("text")
                        .HasColumnName("metaforce_nft_id");

                    b.Property<string>("NftDescription")
                        .HasColumnType("text")
                        .HasColumnName("nft_description");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("properties");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("UnrealItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unreal_item_id");

                    b.HasKey("ItemId")
                        .HasName("items_pkey");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("idx_inventory");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.MissionObjectives", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MissionId")
                        .HasColumnType("text")
                        .HasColumnName("mission_id");

                    b.Property<string>("ObjectiveId")
                        .HasColumnType("text")
                        .HasColumnName("objective_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "MissionId", "ObjectiveId")
                        .HasName("mission_objectives_pkey");

                    b.ToTable("mission_objectives", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.PlayerLocation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level_name");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("double precision")
                        .HasColumnName("x_coordinate");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("double precision")
                        .HasColumnName("y_coordinate");

                    b.Property<double>("ZCoordinate")
                        .HasColumnType("double precision")
                        .HasColumnName("z_coordinate");

                    b.HasKey("UserId")
                        .HasName("player_location_pkey");

                    b.ToTable("player_locations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Session", b =>
                {
                    b.Property<Guid>("InternalSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internal_session_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid>("ExternalSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_session_id");

                    b.Property<string>("OpenMatchTicket")
                        .HasColumnType("text")
                        .HasColumnName("open_match_ticket");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InternalSessionId")
                        .HasName("user_sessions_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_sessions_user_id_idx");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.StoreItem", b =>
                {
                    b.Property<Guid>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internal_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<bool>("IsMultiPurchasable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_multi_purchasable");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("StoreType")
                        .HasColumnType("integer")
                        .HasColumnName("store_type");

                    b.Property<string>("UnrealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unreal_id");

                    b.HasKey("InternalId")
                        .HasName("PK_store_items");

                    b.HasIndex("UnrealId")
                        .IsUnique()
                        .HasDatabaseName("IX_store_items_unreal_id");

                    b.ToTable("store_items", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Stream", b =>
                {
                    b.Property<Guid>("StreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stream_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("StreamId");

                    b.ToTable("streams", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserActiveCustomization", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type");

                    b.Property<string>("UnrealId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unreal_id");

                    b.HasKey("UserId", "SlotType");

                    b.HasIndex("UserId", "UnrealId");

                    b.ToTable("user_active_customizations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvailableCustomization", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UnrealId")
                        .HasColumnType("text")
                        .HasColumnName("unreal_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("properties");

                    b.HasKey("UserId", "UnrealId");

                    b.ToTable("user_available_customizations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvatar", b =>
                {
                    b.Property<Guid>("UserAvatarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_avatar_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_gender");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserAvatarId")
                        .HasName("user_avatars_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_avatars_user_id_idx");

                    b.ToTable("user_avatars", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("BitForceAmount")
                        .HasColumnType("decimal(36, 18)")
                        .HasColumnName("bit_force_amount");

                    b.Property<decimal>("HardAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("hard_amount");

                    b.Property<decimal>("SoftAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soft_amount");

                    b.HasKey("UserId");

                    b.ToTable("user_balances", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalanceTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionId"));

                    b.Property<decimal>("AmountDifference")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount_difference");

                    b.Property<int>("CoinType")
                        .HasColumnType("int")
                        .HasColumnName("coin_type");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId")
                        .HasName("transactions_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_balance_transactions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserEmotion", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UnrealId")
                        .HasColumnType("text")
                        .HasColumnName("unreal_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("UserId", "UnrealId")
                        .HasName("PK_user_emotion_unreal");

                    b.ToTable("user_emotions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer")
                        .HasColumnName("user_status");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("user_status = 0");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserMission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MissionId")
                        .HasColumnType("text")
                        .HasColumnName("mission_id");

                    b.Property<DateTimeOffset?>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<int>("MissionType")
                        .HasColumnType("integer")
                        .HasColumnName("mission_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "MissionId")
                        .HasName("user_missions_pkey");

                    b.ToTable("user_missions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserRelation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RelationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("relation_user_id");

                    b.Property<int>("BlockStatus")
                        .HasColumnType("integer")
                        .HasColumnName("block_status");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FriendStatus")
                        .HasColumnType("integer")
                        .HasColumnName("friend_status");

                    b.HasKey("UserId", "RelationUserId")
                        .HasName("user_relations_pkey");

                    b.HasIndex("RelationUserId");

                    b.ToTable("user_relations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserStorePurchase", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("StoreItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_item_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("UserId", "StoreItemId")
                        .HasName("PK_user_store_purchases");

                    b.HasIndex("StoreItemId");

                    b.ToTable("user_store_purchases", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserTransport", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("TransportUnrealId")
                        .HasColumnType("text")
                        .HasColumnName("transport_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "TransportUnrealId")
                        .HasName("user_transport_pkey");

                    b.ToTable("user_transports", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.AuctionLot", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Auction", "Auction")
                        .WithMany("AuctionLots")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "CurrentBidUser")
                        .WithMany()
                        .HasForeignKey("CurrentBidUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeoDaoBackend.Models.db.Item", "InventoryItem")
                        .WithOne()
                        .HasForeignKey("NeoDaoBackend.Models.db.AuctionLot", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("AuctionLots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("CurrentBidUser");

                    b.Navigation("InventoryItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Channel", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId");

                    b.HasOne("NeoDaoBackend.Models.db.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.ChatMessage", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Channel");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Equipment", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Inventory", "Inventory")
                        .WithMany("Equipments")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipment_inventory_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.Item", "Item")
                        .WithOne()
                        .HasForeignKey("NeoDaoBackend.Models.db.Equipment", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments_item_id_fkey");

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Group", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne("Inventory")
                        .HasForeignKey("NeoDaoBackend.Models.db.Inventory", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("inventory_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Item", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("items_inventory_id_fkey");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.MissionObjectives", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.UserMission", "UserMission")
                        .WithMany("Objectives")
                        .HasForeignKey("UserId", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMission");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.PlayerLocation", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne()
                        .HasForeignKey("NeoDaoBackend.Models.db.PlayerLocation", "UserId")
                        .IsRequired()
                        .HasConstraintName("player_location_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Session", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("user_sessions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserActiveCustomization", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserActiveCustomizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.UserAvailableCustomization", "AvailableCustomization")
                        .WithMany()
                        .HasForeignKey("UserId", "UnrealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_active_customizations_user_available_customizations");

                    b.Navigation("AvailableCustomization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvailableCustomization", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserAvailableCustomizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvatar", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserAvatars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_avatars_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalance", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("NeoDaoBackend.Models.db.UserBalance", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalanceTransaction", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserEmotion", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserEmotions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserGroup", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserMission", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserMissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_missions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserRelation", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "RelationUser")
                        .WithMany()
                        .HasForeignKey("RelationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserStorePurchase", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.StoreItem", "StoreItem")
                        .WithMany("UserStorePurchases")
                        .HasForeignKey("StoreItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserStorePurchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StoreItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserTransport", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Auction", b =>
                {
                    b.Navigation("AuctionLots");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.StoreItem", b =>
                {
                    b.Navigation("UserStorePurchases");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.User", b =>
                {
                    b.Navigation("AuctionLots");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Sessions");

                    b.Navigation("UserActiveCustomizations");

                    b.Navigation("UserAvailableCustomizations");

                    b.Navigation("UserAvatars");

                    b.Navigation("UserBalance")
                        .IsRequired();

                    b.Navigation("UserEmotions");

                    b.Navigation("UserMissions");

                    b.Navigation("UserStorePurchases");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserMission", b =>
                {
                    b.Navigation("Objectives");
                });
#pragma warning restore 612, 618
        }
    }
}
