// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoDaoBackend.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoDaoBackend.Migrations
{
    [DbContext(typeof(NeoDaoDbContext))]
    [Migration("20240729092003_Balance_Transactions")]
    partial class Balance_Transactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoDaoBackend.Models.db.Channel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("NotificationA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notificationA");

                    b.Property<bool>("NotificationB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notificationB");

                    b.Property<DateTimeOffset>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("userA");

                    b.Property<Guid?>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("userB");

                    b.HasKey("ChannelId")
                        .HasName("channels_pkey");

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("channels", (string)null);

                    b.HasData(
                        new
                        {
                            ChannelId = "global",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotificationA = false,
                            NotificationB = false,
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChannelId = "admin",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotificationA = false,
                            NotificationB = false,
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ChannelId = "greetings",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NotificationA = false,
                            NotificationB = false,
                            Updated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.ChatMessage", b =>
                {
                    b.Property<long>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageID"));

                    b.Property<string>("ChannelID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("SenderID")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("MessageID")
                        .HasName("messages_pkey");

                    b.HasIndex("ChannelID");

                    b.HasIndex("SenderID");

                    b.ToTable("chat_messages", (string)null);

                    b.HasData(
                        new
                        {
                            MessageID = 1L,
                            ChannelID = "greetings",
                            Created = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Message = "Welcome to Neo Dao"
                        });
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.ClothingItem", b =>
                {
                    b.Property<string>("ClothesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("clothes_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("ClothesId")
                        .HasName("clothing_items_pkey");

                    b.ToTable("clothing_store_items", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Customization", b =>
                {
                    b.Property<Guid>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internal_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CustomizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customization_id");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("InternalId")
                        .HasName("customization_store_pkey");

                    b.HasIndex("CustomizationId")
                        .IsUnique()
                        .HasDatabaseName("idx_customization_id");

                    b.ToTable("customization_store", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Emotion", b =>
                {
                    b.Property<Guid>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internal_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("EmotionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emotion_id");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("InternalId")
                        .HasName("emotions_pkey");

                    b.HasIndex("EmotionId")
                        .IsUnique()
                        .HasDatabaseName("uq_emotion_id");

                    b.ToTable("emotions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Equipment", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("InventoryId", "SlotType")
                        .HasName("equipments_pkey");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("idx_equipment_item_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("group_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LeaderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_user_id");

                    b.HasKey("GroupId");

                    b.HasIndex("LeaderUserId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InventoryId")
                        .HasName("inventory_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_unique_user")
                        .IsUnique();

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("properties");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("UnrealItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unreal_item_id");

                    b.HasKey("ItemId")
                        .HasName("items_pkey");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("idx_inventory");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.MissionObjectives", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MissionId")
                        .HasColumnType("text")
                        .HasColumnName("mission_id");

                    b.Property<string>("ObjectiveId")
                        .HasColumnType("text")
                        .HasColumnName("objective_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "MissionId", "ObjectiveId")
                        .HasName("mission_objectives_pkey");

                    b.ToTable("mission_objectives", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.PlayerLocation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level_name");

                    b.Property<string>("Tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("double precision")
                        .HasColumnName("x_coordinate");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("double precision")
                        .HasColumnName("y_coordinate");

                    b.Property<double>("ZCoordinate")
                        .HasColumnType("double precision")
                        .HasColumnName("z_coordinate");

                    b.HasKey("UserId")
                        .HasName("player_location_pkey");

                    b.ToTable("player_locations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Session", b =>
                {
                    b.Property<Guid>("InternalSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internal_session_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid>("ExternalSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_session_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InternalSessionId")
                        .HasName("user_sessions_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_sessions_user_id_idx");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Transport", b =>
                {
                    b.Property<string>("TransportUnrealId")
                        .HasColumnType("text")
                        .HasColumnName("transport_id");

                    b.HasKey("TransportUnrealId");

                    b.ToTable("transports", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvatar", b =>
                {
                    b.Property<Guid>("UserAvatarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_avatar_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_gender");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserAvatarId")
                        .HasName("user_avatars_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_avatars_user_id_idx");

                    b.ToTable("user_avatars", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("SoftAmount")
                        .HasColumnType("integer")
                        .HasColumnName("soft_amount");

                    b.HasKey("UserId");

                    b.ToTable("user_balances", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalanceTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionId"));

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("SoftDifference")
                        .HasColumnType("integer")
                        .HasColumnName("soft_difference");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId")
                        .HasName("transactions_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_balance_transactions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserClothesPurchase", b =>
                {
                    b.Property<Guid>("ClothesPurchasesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("clothes_purchases_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ClothesId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clothes_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ClothesPurchasesId")
                        .HasName("user_clothes_purchases_pkey");

                    b.HasIndex("ClothesId");

                    b.HasIndex("UserId", "ClothesId")
                        .IsUnique();

                    b.ToTable("user_clothes_purchases", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserCustomization", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type");

                    b.Property<Guid>("InternalCustomizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_customization_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("properties");

                    b.HasKey("UserId", "SlotType");

                    b.HasIndex("InternalCustomizationId");

                    b.ToTable("user_customizations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserCustomizationPurchase", b =>
                {
                    b.Property<Guid>("UserCustomizationPurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_customization_purchase_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("InternalCustomizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_customization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserCustomizationPurchaseId")
                        .HasName("user_customizations_purchases_pkey");

                    b.HasIndex("InternalCustomizationId");

                    b.HasIndex("UserId", "InternalCustomizationId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserCustomizationPurchases_UserId_InternalCustomizationId");

                    b.ToTable("user_customization_purchases", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserEmotionsPurchase", b =>
                {
                    b.Property<Guid>("EmotionsPurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("emotions_purchases_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("InternalEmotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_emotion_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EmotionsPurchaseId")
                        .HasName("user_emotions_purchases_pkey");

                    b.HasIndex("InternalEmotionId");

                    b.HasIndex("UserId", "InternalEmotionId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_emotions_purchases_user_id_internal_emotion_id");

                    b.ToTable("user_emotions_purchases", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer")
                        .HasColumnName("user_status");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("user_status = 0");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserMission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("MissionId")
                        .HasColumnType("text")
                        .HasColumnName("mission_id");

                    b.Property<DateTimeOffset?>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<int>("MissionType")
                        .HasColumnType("integer")
                        .HasColumnName("mission_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "MissionId")
                        .HasName("user_missions_pkey");

                    b.ToTable("user_missions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserRelation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RelationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("relation_user_id");

                    b.Property<int>("BlockStatus")
                        .HasColumnType("integer")
                        .HasColumnName("block_status");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FriendStatus")
                        .HasColumnType("integer")
                        .HasColumnName("friend_status");

                    b.HasKey("UserId", "RelationUserId")
                        .HasName("user_relations_pkey");

                    b.HasIndex("RelationUserId");

                    b.ToTable("user_relations", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserTransport", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("TransportUnrealId")
                        .HasColumnType("text")
                        .HasColumnName("transport_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "TransportUnrealId")
                        .HasName("user_transport_pkey");

                    b.HasIndex("TransportUnrealId");

                    b.ToTable("user_transports", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Channel", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId");

                    b.HasOne("NeoDaoBackend.Models.db.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.ChatMessage", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID");

                    b.Navigation("Channel");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Equipment", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Inventory", "Inventory")
                        .WithMany("Equipments")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments_inventory_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.Item", "Item")
                        .WithOne()
                        .HasForeignKey("NeoDaoBackend.Models.db.Equipment", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments_item_id_fkey");

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Group", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne("Inventory")
                        .HasForeignKey("NeoDaoBackend.Models.db.Inventory", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("inventory_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Item", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("items_inventory_id_fkey");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.MissionObjectives", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.UserMission", "UserMission")
                        .WithMany("Objectives")
                        .HasForeignKey("UserId", "MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMission");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.PlayerLocation", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne()
                        .HasForeignKey("NeoDaoBackend.Models.db.PlayerLocation", "UserId")
                        .IsRequired()
                        .HasConstraintName("player_location_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Session", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("user_sessions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvatar", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserAvatars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_avatars_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalance", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("NeoDaoBackend.Models.db.UserBalance", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserBalanceTransaction", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserClothesPurchase", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.ClothingItem", "ClothingItem")
                        .WithMany()
                        .HasForeignKey("ClothesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_clothes_purchases_clothing_item_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_clothes_purchases_user_id_fkey");

                    b.Navigation("ClothingItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserCustomization", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Customization", "Customization")
                        .WithMany()
                        .HasForeignKey("InternalCustomizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("users_customizations_internal_customization_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("users_customizations_user_id_fkey");

                    b.Navigation("Customization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserCustomizationPurchase", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Customization", "Customization")
                        .WithMany()
                        .HasForeignKey("InternalCustomizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_customizations_purchases_internal_customization_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_customizations_purchases_user_id_fkey");

                    b.Navigation("Customization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserEmotionsPurchase", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Emotion", "Emotion")
                        .WithMany()
                        .HasForeignKey("InternalEmotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_emotions_purchases_emotion_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_emotions_purchases_user_id_fkey");

                    b.Navigation("Emotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserGroup", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserMission", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserMissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_missions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserRelation", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "RelationUser")
                        .WithMany()
                        .HasForeignKey("RelationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelationUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserTransport", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportUnrealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.User", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Sessions");

                    b.Navigation("UserAvatars");

                    b.Navigation("UserBalance")
                        .IsRequired();

                    b.Navigation("UserMissions");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserMission", b =>
                {
                    b.Navigation("Objectives");
                });
#pragma warning restore 612, 618
        }
    }
}
