// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoDaoBackend.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoDaoBackend.Migrations
{
    [DbContext(typeof(NeoDaoDbContext))]
    [Migration("20240612111136_CompanionsAndEquipments")]
    partial class CompanionsAndEquipments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoDaoBackend.Models.db.Companion", b =>
                {
                    b.Property<Guid>("CompanionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("companion_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CompanionKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("companion_kind");

                    b.Property<string>("CompanionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("companion_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("CompanionId")
                        .HasName("companions_pkey");

                    b.ToTable("companions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Equipment", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.HasKey("InventoryId", "SlotType")
                        .HasName("equipments_pkey");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("idx_equipment_item_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InventoryId")
                        .HasName("inventory_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_unique_user")
                        .IsUnique();

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CompanionId")
                        .HasColumnType("uuid")
                        .HasColumnName("companion_id");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int?>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("ItemId")
                        .HasName("items_pkey");

                    b.HasIndex("CompanionId");

                    b.HasIndex(new[] { "InventoryId" }, "idx_inventory");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Session", b =>
                {
                    b.Property<Guid>("InternalSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internal_session_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid>("ExternalSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_session_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InternalSessionId")
                        .HasName("user_sessions_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_sessions_user_id_idx");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvatar", b =>
                {
                    b.Property<Guid>("UserAvatarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_avatar_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_gender");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserAvatarId")
                        .HasName("user_avatars_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_avatars_user_id_idx");

                    b.ToTable("user_avatars", (string)null);
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Equipment", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Inventory", "Inventory")
                        .WithMany("Equipments")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments_inventory_id_fkey");

                    b.HasOne("NeoDaoBackend.Models.db.Item", "Item")
                        .WithOne()
                        .HasForeignKey("NeoDaoBackend.Models.db.Equipment", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("equipments_item_id_fkey");

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithOne("Inventory")
                        .HasForeignKey("NeoDaoBackend.Models.db.Inventory", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("inventory_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Item", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.Companion", "Companion")
                        .WithMany()
                        .HasForeignKey("CompanionId");

                    b.HasOne("NeoDaoBackend.Models.db.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("items_inventory_id_fkey");

                    b.Navigation("Companion");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Session", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("user_sessions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.UserAvatar", b =>
                {
                    b.HasOne("NeoDaoBackend.Models.db.User", "User")
                        .WithMany("UserAvatars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("user_avatars_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.Inventory", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("NeoDaoBackend.Models.db.User", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Sessions");

                    b.Navigation("UserAvatars");
                });
#pragma warning restore 612, 618
        }
    }
}
