apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: neodao-mine-autoscaler
  namespace: default
spec:
  fleetName: neodao-mine
  policy:
    type: Buffer
    buffer:
      minReplicas: 2
      maxReplicas: 50
      bufferSize: 2 # change on production
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: neodao-capital-autoscaler
  namespace: default
spec:
  fleetName: neodao-capital
  policy:
    type: Buffer
    buffer:
      minReplicas: 2
      maxReplicas: 50
      bufferSize: 2 #change on production