apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: neodao-mine
  namespace: default
spec:
  replicas: 5
  template:
    metadata:
      labels:
        agones.dev/fleet: Mine
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7777
          protocol: UDP
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      players:
        initialCapacity: 10
      template:
        metadata:
          labels:
            agones.dev/fleet: Mine
        spec:
          containers:
            - name: neodao-mine
              image: registry.digitalocean.com/metaforce/neodao-dedicated-server:mm-dev
              imagePullPolicy: Always
              args: ["/Game/Metacity/Art/Maps/Mine/L_map_Mine?listen", "-server"]
              resources:
                requests:
                  memory: "2Gi" 
                  cpu: "1000m"  
                limits:
                  memory: "4Gi" 
                  cpu: "2000m" 
          imagePullSecrets:
            - name: registry-metaforce
---
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: neodao-capital
  namespace: default
spec:
  replicas: 5
  template:
    metadata:
      labels:
        agones.dev/fleet: Capital
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7777
          protocol: UDP
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      players:
        initialCapacity: 10
      template:
        metadata:
          labels:
            agones.dev/fleet: Capital
        spec:
          containers:
            - name: neodao-capital
              image: registry.digitalocean.com/metaforce/neodao-dedicated-server:mm-dev
              imagePullPolicy: Always
              args: ["/Game/Metacity/Art/Maps/Demo_Hotelmap/L_Demo_mapHotel?listen", "-server"]
              resources:
                requests:
                  memory: "2Gi" 
                  cpu: "1000m" 
                limits:
                  memory: "4Gi" 
                  cpu: "2000m" 
          imagePullSecrets:
            - name: registry-metaforce