apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/elasticsearch"
  volumeMode: Filesystem
