apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-alertmanager-pv
  namespace: metrics
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/alertmanager
