apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-prometheus-server
  namespace: metrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: standard
